######################################################################
# Automatically generated by qmake (3.0) Sun Jan 24 21:32:21 2016
######################################################################

CONFIG += debug
TEMPLATE = app
TARGET = caracas-gui
INCLUDEPATH += .
QT += core gui widgets
#LIBS += -lmarblewidget

# Input
HEADERS = mainscreen.hpp mapscreen.hpp diagnosticscreen.hpp
SOURCES = mainscreen.cpp mapscreen.cpp diagnosticscreen.cpp main.cpp
