install:
	install -v -t /etc/init.d card proxy sigd cmpd suicide webservice
	update-rc.d card defaults
	update-rc.d proxy defaults
	update-rc.d sigd defaults
	update-rc.d cmpd defaults
	update-rc.d suicide defaults
	update-rc.d webservice defaults
