#! /bin/sh
### BEGIN INIT INFO
# Provides:          suicide
# Required-Start:    $local_fs
# Required-Stop:     halt
# X-Stop-After:      umountroot
# Default-Start:     2 3 4 5
# Default-Stop:      0
# Short-Description: Enable the suicide pin
# Description:
### END INIT INFO

. /lib/lsb/init-functions

do_start () {
    log_action_msg "Disabling the suicide pin"
    /usr/local/bin/gpio mode 25 out
    /usr/local/bin/gpio write 25 0
}

do_stop () {
    log_action_msg "Enabling the suicide pin, goodbye cruel world"
    /bin/sync
    /usr/local/bin/gpio mode 25 out
    /usr/local/bin/gpio write 25 1
}

case "$1" in
    start)
        do_start
        case "$?" in
            0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
            2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
        do_stop
        case "$?" in
            0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
            2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac

:
